---
apiVersion: v1
appVersion: "v0.10.0"
description: Druid exporter to monitor druid metrics with Prometheus
engine: gotpl
name: prometheus-druid-exporter
version: 0.10.0
home: https://github.com/opstree/druid-exporter
maintainers:
- email: abhishekbhardwaj510@gmail.com
  name: iamabhishek-dubey
- email: sandeep@opstree.com
  name: sandy724
- email: stephan.stiefel@hawk.ai
  name: Stephan3555
sources:
  - https://github.com/opstree/druid-exporter/helm
keywords:
- kubernetes
- apache
- druid
- exporter
- prometheus
- grafana
icon: https://github.com/opstree/druid-exporter/blob/master/static/druid-exporter-logo.svg
